language: node_js

os:
  - linux
  - osx
  - windows

group: dev

after_success: if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run coverage; fi

#cache:
#  directories:
#    - "node_modules"

node_js:
  - "6"
  - "8"
  - "10"

